//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGara
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHU
    {
        public string SoPT { get; set; }
        public Nullable<System.DateTime> NgayLapPT { get; set; }
        public int SoHD { get; set; }
        public int MaKH { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> SoTienThu { get; set; }
    
        public virtual HOPDONG HOPDONG { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
