//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGara
{
    using System;
    using System.Collections.Generic;
    
    public partial class THO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THO()
        {
            this.THO1 = new HashSet<THO>();
        }
    
        public int MaTho { get; set; }
        public string TenTho { get; set; }
        public Nullable<int> Nhom { get; set; }
        public Nullable<int> NhomTruong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THO> THO1 { get; set; }
        public virtual THO THO2 { get; set; }
    }
}
